### ISSUE TITLE
Point Light Shadows not working

### ISSUE THREAD

**Issue by HellGate94** [raphael-ernaelsten/Aura#1]
Directional and Spotlight are working fine but Point light have no shadows and shine through everything.

![image](https://user-images.githubusercontent.com/8095602/36104942-aad37e8c-1013-11e8-86d8-d50eebfb6c8e.png)

Unity 2017.3.1f1

**Comment by raphael-ernaelsten** [comment]
This is known on 2017.3. It will be fixed.
As stated in FAQ, release is for 2017.2.

**Comment by simeonradivoev** [comment]
Using `UnitySampleShadowmap` instead of `SampleCubeDistance` in the shader `Hidden/Aura/StorePointLightShadowMap` kinda works but the shadows aren't right. Also there must be a `SHADOWS_CUBE_IN_DEPTH_TEX` defined check in shader.

**Comment by raphael-ernaelsten** [comment]
Yes that is indeed something like that I must change the shader into.
Thanks! I'll take your track and investigate.

**Comment by raphael-ernaelsten** [comment]
Fixed!
Now successfully working on all Unity version from 2017.2
