### ISSUE TITLE
Aura Light scripts are unenabled everytime I open the project

### ISSUE THREAD

**Issue by Paincho** [raphael-ernaelsten/Aura#11]
on Unity 2018.1.0b7

**Comment by raphael-ernaelsten** [comment]
Is the camera with the main component present? If not, it should as the lights register to it. If it's not present, the lights cannot register then are disabled.

**Comment by Paincho** [comment]
The "Aura" component is attached to the main camera yes.

**Comment by raphael-ernaelsten** [comment]
Working good for everyone but you.
Must be endogenous to your scene(s). Make sure the component is present and enabled(and the gameobject) before loading the lights.

**Comment by Joybutton** [comment]
Hi Raphael! First, Aura is simply amazing. Thank you so much for all your hard work. I very much look forward to having your logo in the credits scroll for the real-time cinematic piece I'm working on!

I actually came here looking for a solution to the same problem as Paincho. Based on your feedback I was able to determine the issue and thought I'd give a little more info.

Paincho, like myself, probably has a multi-camera script that starts when the scene loads and activates the appropriate camera. All the cameras are disabled until the scene starts. Even having the script on the main camera, you can't activate the Aura Light scripts in the Inspector unless the scene is currently running (and the camera is enabled via script).

Now that I understand what's going on I'm working on getting the camera switching script to enable the Aura Light scripts after it enables the camera. Is that the best way to deal with this particular situation?

**Comment by Paincho** [comment]
That's the solution I implemented this morning once I'm sure everything is in place I enable the lights.

**Comment by raphael-ernaelsten** [comment]
That's indeed currently the best way to deal with these use cases.

**Comment by raphael-ernaelsten** [comment]
Good! I am glad.
