### ISSUE TITLE
Null Reference Exception

### ISSUE THREAD

**Issue by JasonAvis** [raphael-ernaelsten/Aura#12]
When I attach the Aura Main Component to the Camera I have in my scene, I get this Null Reference:

NullReferenceException: Object reference not set to an instance of an object
AuraAPI.Aura.DisposeFrustrum () (at Assets/Aura/Classes/Aura.cs:359)
AuraAPI.Aura.OnDisable () (at Assets/Aura/Classes/Aura.cs:149)
UnityEngine.Behaviour:set_enabled(Boolean)
AuraAPI.Aura:OnEnable() (at Assets/Aura/Classes/Aura.cs:135)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

I am using Unity 2017.3.0f3.

**Comment by raphael-ernaelsten** [comment]
Please read the ReadMe

**Comment by JasonAvis** [comment]
I'm sorry but I looked through the ReadMe and I am not seeing what I am missing. From how the Getting Started section reads I just need to put the Aura Main Component on the Main Camera and put some Aura Lights in the scene which I have done.

**Comment by raphael-ernaelsten** [comment]
In the readme on the front page of the repository, in the requirements section, there is a paragraph in bold talking about this very specific case.

**Comment by JasonAvis** [comment]
Oh I apologize, I was looking the the Starting Guide, not the ReadMe... My mistake.
