### ISSUE TITLE
Ambient density darkens scene dramatically

### ISSUE THREAD

**Issue by JeffBenjamin** [raphael-ernaelsten/Aura#14]
Unity version 2017.3.0f3

Created an brand new empty scene, added an Aura Main Component on the Main Camera, turned Ambient Light Strength to 0.  The expected behaviour in my mind is that the scene should look unchanged, however i'm finding everything gets quite dark with any ambient density values above 0.  Am I missing something?

Included before and after screenshots below:

Before - 
![image](https://user-images.githubusercontent.com/36869352/36705267-159eb8d4-1b19-11e8-9b5a-efb46e6aef64.png)

After setting Ambient density to .25 and Ambient Light Strength to 0-
![image](https://user-images.githubusercontent.com/36869352/36705289-3043e0ba-1b19-11e8-9442-5a6441457443.png)

**Comment by raphael-ernaelsten** [comment]
Just think about it...
Air now have density, micro particles that are now visible... If there are visible light rays, it'll be because there are receiving entities.
Read the StartingGuide ;)

**Comment by JeffBenjamin** [comment]
I guess I had expected there to be no contribution to the scene without a light source.  Maybe I should rephrase the issue as a question instead:

The behavior I would like to achieve is 0 ambient density in areas not directly lit by an aura light (and therefore no overall darkening of my scene).  Areas lit by an aura light would have a > 0 density.  Is there a way to achieve this behavior without using the primitive injection volumes?

**Comment by raphael-ernaelsten** [comment]
Read the Starting Guide (this time without smiley)
