### ISSUE TITLE
Can not get the light shafts to look as crisp as in the screenshots.

### ISSUE THREAD

**Issue by Kulgann** [raphael-ernaelsten/Aura#20]
I imported the newest version into my project on Unity 2017.3.1f1 and I  opened one of the example scenes. The cave to be precise. Increasing the grid resolution does not yield any resulst and at about 512x512 the editor starts to lag horribly. What am I doing wrong?

**Comment by raphael-ernaelsten** [comment]
The resolution used for the recordings was 320*176*256.
I also used PostProcessing Stack with TXAA.
