### ISSUE TITLE
Unity 2018 - Beta 11 - Not importing

### ISSUE THREAD

**Issue by VisualTech48** [raphael-ernaelsten/Aura#22]
While 2018 is in the dev build, I'm reporting that I always get stuck on the .compute file in 2018 while importing it

**Comment by JonDadley** [comment]
I have succesfully imported Aura into beta 11. Please not, as mentioned in the Aura readme:

"The main ComputeShader has many variants (for performance purposes). This will lead its compilation, and therefore the import of the package in Unity, to take a long time (usually from 20 minutes to an hour!). PLEASE DO NOT KILL UNITY AND WAIT UNTIL THE IMPORT IS DONE. If you did kill Unity, or experienced any trouble, during importation, you'll get a "NullReference Exception", re-import the file Aura/Shaders/ComputeShaders/ComputeDataComputeShader.compute"

**Comment by VisualTech48** [comment]
My mistake, sorry for that, since I have an I7 I thought it couldn't be longer than 30 minutes so I killed it.
Will read the readme in detail before any issues I submit. 

Thank you
