### ISSUE TITLE
Single pass stereo, additive scene loading

### ISSUE THREAD

**Issue by kristianpd** [raphael-ernaelsten/Aura#23]
We were playing with Aura in our single pass stereo (i know it's not officially supported) game. I noticed something that I'm not sure is related to lack of single pass stereo support, but rather more related to some kind of race/assumptions about how the camera is loaded.

We load our VR runtime in an additive scene, so it's not there when unity starts up. If i do this, with aura, on multi pass, it seems fine. If i do this, with aura, on single pass, i get a weird stereo lensing effect when I switch to our VR headset (the one with Aura script on camera).

Disable:
![image](https://user-images.githubusercontent.com/378038/38100656-f9b9a53e-334b-11e8-8b96-512cd131925a.png)

Enable: 
![image](https://user-images.githubusercontent.com/378038/38100634-ee1c4ff6-334b-11e8-9a10-d226de977d3c.png)

Tracking this down a bit more, the specific option that appears to "fix it" is `Apply As PostProcess`

![image](https://user-images.githubusercontent.com/378038/38100622-e42a17bc-334b-11e8-90e6-cf7498231654.png)

When this option is on, i get the weird camera lensing effect, when off, it's fine. 

## I think it's more of an additive scene loading problem

Even though single pass isn't officially supported, as I said above I think this is more of a order of operations type problem.

You'll notice in my screenshots that my `VR` prefab is in the `Runtime` scene. If i add this `VR` prefab directly to my main scene (not loaded at runtime), I do **not** experience these problems (regardless of aura/postprocess toggle state).

## Reproduction
I'm not really familiar with the whole Aura setup yet, but I suspect this can be reproduced for testing by having an additive scene load your VR camera with Aura on it. 

Hope this helps, let me know if you want any more information!

**Comment by raphael-ernaelsten** [comment]
I could expect that kind of behaviour as nothing has been done to handle single pass case. Wait for more investigation on single pass.
