### ISSUE TITLE
Aura not working

### ISSUE THREAD

**Issue by alexeykuznetsov** [raphael-ernaelsten/Aura#25]
Just added Aura in my project, opened Directional Light Example scene and played it.
Result: no any volumetric effect. 
On load scene console always have this error:

NullReferenceException: Object reference not set to an instance of an object
AuraAPI.Frustum.Dispose () (at Assets/Aura/Classes/Frustum.cs:330)
AuraAPI.Aura.DisposeFrustrum () (at Assets/Aura/Classes/Aura.cs:359)
AuraAPI.Aura.OnDisable () (at Assets/Aura/Classes/Aura.cs:149)
UnityEngine.Behaviour:set_enabled(Boolean)
AuraAPI.Aura:OnEnable() (at Assets/Aura/Classes/Aura.cs:135)

Tried on Unity versions  2018.1.02f and Unity 2017.3.1f1.

**Comment by raphael-ernaelsten** [comment]
Please read the readme
