### ISSUE TITLE
Directional Light

### ISSUE THREAD

**Issue by IE585** [raphael-ernaelsten/Aura#27]
![22](https://user-images.githubusercontent.com/21693678/40009443-af430cc4-57aa-11e8-909e-123225677678.png)
Other light sources work fine except for the main one which is shown on the screen. The error disappears when Directional Ligt is turned off and on.

**Comment by raphael-ernaelsten** [comment]
could you track down which specific CopyTexture throws that error?

**Comment by IE585** [comment]
As I understand it is a shadow in the script of the aura, when they are disabled, the error disappears, but the script itself does not work correctly. Have you checked the compatibility with the new version of the engine? Just the rest of the lighting works fine.

**Comment by IE585** [comment]
Thanks, I will wait.

**Comment by garv3** [comment]
Get the same error in 2018.2x prefab preview version. No fix available?

**Comment by zacman5001** [comment]
Also having this issue in 2018.2.0f2

**Comment by JamesMcGhee** [comment]
We can confirm this issue with directional light on Unity 2018.2.x and with the same behavior e.g. the issue will happen each frame after a load however if you disable and enable the light it will apparently be corrected e.g. no error spam any more and the light seems to behave. If you start with the light off then turn it on after load no issue.

**Comment by jwinder86** [comment]
I'm also seeing this issue in 2018.2.0f2

The problem occurs specifically for directional lights with shadows enabled.  Directional lights without shadows work fine, as do point and spot lights with shadows.

The problem seems to be occuring in Texture2DArrayComposer.cs [line 195](https://github.com/raphael-ernaelsten/Aura/blob/master/Assets/Aura/Classes/Texture2DArrayComposer.cs#L195)

**Comment by jwinder86** [comment]
I managed to hunt down the source of the problem: AuraLight.shadowDataRenderTexture is getting serialized and saving some non-null value in the scene.

Unfortunately the code only initializes AuraLight.shadowRenderTexture when the value is null, so the serialized value prevents correct initialization.  [see here.](https://github.com/raphael-ernaelsten/Aura/blob/f3c51ed3650592c5b73bfe0d567686c41a1aafed/Assets/Aura/Classes/AuraLight.cs#L389-L392)

I was able to fix this by turning off serialization for shadowDataRenderTexture, by adding [System.NonSerialized] to this field.  Directional lights with shadow work correctly and no errors are logged after making this change.

**Comment by crystalbyte** [comment]
Unfortunately this did not solve my issue :(

**Comment by raphael-ernaelsten** [comment]
I have no more errors with the next update. Please wait for it.

**Comment by crystalbyte** [comment]
Is there a date for the next update ?

**Comment by davl3232** [comment]
@jwinder86 your solution worked for me. Thank you.
