### ISSUE TITLE
Is it possible to roughly sample Aura density in an arbitrary fragment shader?

### ISSUE THREAD

**Issue by artyom-zuev** [raphael-ernaelsten/Aura#29]
I'm trying to make a crude fix for transparent shaders (which stand out in a bad way in any foggy scenario). While all transparent shaders don't write to depth, they do know their exact depth at the moment of fragment execution. So, I'd love to calculate fog density and lerp toward fog color based on it to make transparent shaders stand out less in dense fog. This is trivial to do with Unity fog, since deriving it's density based on fragment depth + some globals is pretty straightforward, but I have no idea where to start implementing that with Aura. I'd really appreciate any pointers. :)

**Comment by raphael-ernaelsten** [comment]
You can entirely have the whole Aura fog like if it was an opaque object.
I guess you should have read the Custom Shaders section in the Starting Guide ;-)
