### ISSUE TITLE
How does this compare to Unity's solution?

### ISSUE THREAD

**Issue by transat** [raphael-ernaelsten/Aura#31]
What are the pros of using this compared to https://github.com/Unity-Technologies/VolumetricLighting ?

**Comment by raphael-ernaelsten** [comment]
Hi what solution exactly are you referring to?

**Comment by InNoHurryToCode** [comment]
On a quick glance (note that I've only experimented with Aura and never played around with Unity's solution):
Aura:
- supports directional lights
- gaia extention
- works on both deferred and forward
It doesn't look like that unity's solution has these features.
As always, if you have the time to play around with both, give them both  a shot and see which is better suited for your needs.

**Comment by transat** [comment]
Raphael - the one in the body of the issue.

Innohurrytocode - cool. I use Gaia so if there’s a good integration that’s a definite plus for me. I’ve yet to play with either aura or the unity volumetric Iighting addon. Still in the learning and preparing phase but can report back if I end up testing both options.

Cheers guys!

**Comment by transat** [comment]
As a follow up... Unity have said they are no longer maintaining the version they have on GitHub.
