### ISSUE TITLE
Multiple cameras

### ISSUE THREAD

**Issue by FelipeDrude** [raphael-ernaelsten/Aura#32]
Hi, thanks for the great project.

So, I was trying to use aura on my project, but I can't seem to make it work on more than one camera, could you tell me if there is way I can make it work, or if i did something wrong.

What happens is, we have two players, and 2 splitscreen cameras with one Aura component each, they make the viewport, that is split, show the images from the same camera (the second one in the case of the print)
![2camerason](https://user-images.githubusercontent.com/23181198/40576411-3c268722-60cc-11e8-9674-13123c118932.JPG)
![onecamera](https://user-images.githubusercontent.com/23181198/40576412-3c488228-60cc-11e8-9f0e-491fcc6c974b.JPG)
![capture2](https://user-images.githubusercontent.com/23181198/40576413-3c69c622-60cc-11e8-8dbf-5792d509ecad.JPG)

thanks

**Comment by raphael-ernaelsten** [comment]
Hi! It's a known limitation of the system right now. It'll be changed in a later update.
