### ISSUE TITLE
Help - Error building Player: 2 errors

### ISSUE THREAD

**Issue by XN4k33Db** [raphael-ernaelsten/Aura#36]
When trying to compile for windows 10 UWP two errors occur:

ERROR 01 
"Shader error in 'Hidden/Aura/ProcessOcclusionTextureShader': forced to unroll loop, but unrolling failed. at line 71 (on d3d11_9x)

Compiling Fragment program
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_NO_CUBEMAP_ARRAY UNITY_NO_SCREENSPACE_SHADOWS UNITY_PBS_USE_BRDF3 SHADER_API_MOBILE UNITY_HARDWARE_TIER1 UNITY_COLORSPACE_GAMMA UNITY_LIGHTMAP_RGBM_ENCODING"

ERROR 02
"Shader error in 'Hidden/Aura/ProcessOcclusionTextureShader': can't use flow control on this profile at line 75 (on d3d11_9x)

Compiling Fragment program
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_NO_CUBEMAP_ARRAY UNITY_NO_SCREENSPACE_SHADOWS UNITY_PBS_USE_BRDF3 SHADER_API_MOBILE UNITY_HARDWARE_TIER1 UNITY_COLORSPACE_GAMMA UNITY_LIGHTMAP_RGBM_ENCODING
"
Can you help me?

**Comment by raphael-ernaelsten** [comment]
Are you sur you're on DX11?

**Comment by XN4k33Db** [comment]
yes

**Comment by XN4k33Db** [comment]
>

**Comment by raphael-ernaelsten** [comment]
Because most compiling errors come from the fact people do not make sure they're on dx11.
Maybe one more UWP-specific weirdness.

**Comment by XN4k33Db** [comment]
Strange, doing exactly nothing could build today.

**Comment by XN4k33Db** [comment]
Dont work on xbox one console... ;(

**Comment by raphael-ernaelsten** [comment]
I think there might be texture format issues with xBoxOne...

2018-06-07 18:52 GMT+02:00 XN4k33Db <notifications@github.com>:
