### ISSUE TITLE
NullReferenceException AuraAPI.AuraVolume.PackData () (at Assets/External/Aura/Classes/AuraVolume.cs:262)

### ISSUE THREAD

**Issue by MrCharli3** [raphael-ernaelsten/Aura#37]
I'm aware of the documented fix for the Import nullrefrence error, however this one is different.
It randomly pops up in editor, cant really figure out when.

`NullReferenceException
AuraAPI.AuraVolume.PackData () (at Assets/External/Aura/Classes/AuraVolume.cs:262)
AuraAPI.AuraVolume.Aura_onPreRenderEvent (UnityEngine.Camera camera) (at Assets/External/Aura/Classes/AuraVolume.cs:195)
AuraAPI.Aura.OnPreRender () (at Assets/External/Aura/Classes/Aura.cs:169)
`

**Comment by timmythetiny** [comment]
The only thing on that line I can think of that could be null would be textureMask.texture.  Could you go to the Aura Volume that's throwing the exception, double click on the Texture Mask slot, and see if the Texture slot has something in it?

**Comment by raphael-ernaelsten** [comment]
What Unity version? 2018.2 BETA seems to be fucked up

**Comment by MrCharli3** [comment]
Seems to have resolved it self. I have no clue how though... Close
