### ISSUE TITLE
Why does Aura Volume and Aura Light disable themselves?

### ISSUE THREAD

**Issue by MrCharli3** [raphael-ernaelsten/Aura#38]
For some reason these two randomly disable themselves. Not during playtime, but while working in the editor, then when I run the game sometimes I'll notice it's disabled. 

Is this something known?

**Comment by MrCharli3** [comment]
Seems it might be every time my scripts compile in the editor. Only connection I can find. Note that I do not edit any of your scripts. Everything is default.

**Comment by AlexanderBalson** [comment]
I'm having the same issue, had to put in a really bad hack to make the components stay enabled. This issue: https://github.com/raphael-ernaelsten/Aura/issues/18 has some possible fixes maybe.

**Comment by VoidFletcher** [comment]
Duplicate issue, have a look at #18

https://github.com/raphael-ernaelsten/Aura/issues/18

There's also a workaround in there (Create an awake script that manually enables all aura light components. It's not ideal but yeah.)

**Comment by raphael-ernaelsten** [comment]
Hi it's a race condition between the Aura main component and the other Aura component. It mostly happens in the most recent versions. It'll be anyway fixed.
