### ISSUE TITLE
Error "event must be of a delegate type"

### ISSUE THREAD

**Issue by R-Dreamer** [raphael-ernaelsten/Aura#41]
Greetings,

I just downloaded Aura on Unity 2017.3.0f3 and again on 2018.2.0b5 and in both versions these errors appear of which I cannot seem to fix or code around.

`AuraAPI.Aura.OnPreRenderEvent': event must be of a delegate type
error CS0066: Assets/Aura/Classes/Aura.cs(106,44)

`AuraAPI.AuraVolume.OnTextureMaskStateChanged': event must be of a delegate type
error CS0066: Assets/Aura/Classes/AuraVolume.cs(97,41)

`AuraAPI.AuraVolume.OnTextureMaskChanged': event must be of a delegate type
error CS0066: Assets/Aura/Classes/AuraVolume.cs(101,41)

**Comment by raphael-ernaelsten** [comment]
Isn't there other compiling errors before? What dotNet version? Is aura alone in the project?

**Comment by johankitti** [comment]
I had similar issues. My problem was I had a class called "Action" in my project that wasn't declared under a namespace and collided with the Aura class Action. I renamed my class and the issues disappeared.

**Comment by raphael-ernaelsten** [comment]
Ho yes indeed!
Action is not a class from Aura, it is a generic delegate for events contained in System.

**Comment by raphael-ernaelsten** [comment]
Thanks @johankitti btw

**Comment by johankitti** [comment]
Oh yes of course! No problem @raphael-ernaelsten !
