### ISSUE TITLE
Parameter name: shader ArgumentNullException

### ISSUE THREAD

**Issue by paulfielding9** [raphael-ernaelsten/Aura#43]
Hi Raphael,

Firstly, thanks for the great asset, it looks fantastic!

When I add a light to my scene, I get the error below. This is in Unity 2018.1.0f on Windows 10 using DirectX11. This is on a fresh import of the asset.

I tried deleting the Aura folder and then deleting the shader cache in the Library folder to force a fresh recompile of the compute shader when I reimport but the error persists.

Error from the Console:

ArgumentNullException: Argument cannot be null.
Parameter name: shader
UnityEngine.Material..ctor (UnityEngine.Shader shader) (at C:/buildslave/unity/build/Runtime/Export/Shader.bindings.cs:97)
AuraAPI.AuraLight.Initialize () (at Assets/Aura/Classes/AuraLight.cs:399)
AuraAPI.AuraLight.OnEnable () (at Assets/Aura/Classes/AuraLight.cs:224)
UnityEngine.GameObject:AddComponent()
AuraAPI.AuraLight:CreateGameObject(MenuCommand, String, LightType) (at Assets/Aura/Classes/AuraLight.cs:746)
AuraAPI.AuraLight:CreateDirectionalGameObject(MenuCommand) (at Assets/Aura/Classes/AuraLight.cs:758)
UnityEditor.GenericMenu:CatchMenu(Object, String[], Int32)

If I open this error from the Console in Visual Studio it highlights this line in AuraLights.cs:
"
                            _storeShadowDataMaterial = new Material(storeShadowDataShader);
"

**Comment by raphael-ernaelsten** [comment]
It must somehow have lost track of the reference shader.

Select AuraLight.cs in Aura/Classes/, watch in the Inspector for the field storeShadowDataShader and assign the  StoreShadowDataShader.shader (located in Aura/Shaders/Shaders/) asset on it.

Then re-try.

**Comment by paulfielding9** [comment]
Hi,

Thanks for coming back so quickly. The shader reference was already currently set to:

"/Hidden/Aura/StoreShadowDataShader"

The Shadow Map Render Texture, Cookie Map Render Texture and Shadow Data Render Texture are all unset though i.e no textures are selected. Should they have textures referenced or is that done at runtime when they're needed?

Interestingly, I only get the console error quoted in my first post above if I add a light via the GameObject / Aura / Light menu. If I add a normal directional light manually and then add the AuraLight.cs component I don't get an error.

Perhaps this isn't a big deal afterall? Seems a bit of a strange error to get though, given the shader is already set in the AuraLight.cs component.

**Comment by raphael-ernaelsten** [comment]
Ho i understand better now. Yes I have encountered this already.
Don't worry. This is a reported Unity bug that has no consequences.

2018-06-13 3:52 GMT+02:00 paulfielding9 <notifications@github.com>:
