### ISSUE TITLE
AuraLight shader issues

### ISSUE THREAD

**Issue by JamesMcGhee** [raphael-ernaelsten/Aura#46]
With 2018.1.5 under HDRP AuraLight does not retain reference to the StoreShadowDataShader or other shaders as referenced in the AuraLight class. I have confirmed the shaders are there and have compiled correctly or at least without error. I also tried a simple search for the shader which did return a value apparently yet none of the Aura effects seem to have any effect.

e.g. in AuraLight.cs to get around the null reference excception due to the mission shader references I replaced the call to storeShadowDataShader with Shader.Find(...) and this seemed to return without error. This was done just to work around the issue ... for note I have yet to see any effect from Aura at all in HDRP so perhaps I am simply missing something obvious.

For note I did check the AuraLight.cs as it appears in the Project view and confirmed the class is referencing the shaders however when you add the componint to the scene you get a Null Reference Exception, if you reset the component you get an error about the various shaders not being set dispite them showing in the class's default 

2nd edit ... its also worth noting that using default references will cause problems even if it was working in this instance. They only apply when a component is set from within the editor, if you where to create an AuraLight from code for example it wouldn't be there and its not obvious anywhere what is expected without looking at the class defaults. A better method is to use Shader.Find("shader name"); and it might be worth making sure that required shaders are added to the 'always include' list of the project settings.

**Comment by raphael-ernaelsten** [comment]
Hi! Thanks for your work. This issue will be addressed in one of the next update.

**Comment by JamesMcGhee** [comment]
I gave it a go on Unity's built in render and got the same null ref issue, used the same work around and saw nice volume lighting effects. So from that I take it that HDRP Aura isn't working at the moment at least not out of the box (ignoreing the Find shader issue) but it does work on the same engine version using Unity's built in renderer once you account for the null ref exceptions.

**Comment by raphael-ernaelsten** [comment]
References are fixed, will be published with next update.
Didn't investigate with SRP yet.
