### ISSUE TITLE
Aura Light components get disabled if the Aura master component is in a different scene

### ISSUE THREAD

**Issue by Rtyper** [raphael-ernaelsten/Aura#5]
Aura Light components seem to get disabled if there's no Aura master component in the scene, which makes sense, however it doesn't take into account multiple scenes being loaded at the same time.

I have my main camera, player objects and all managers etc in a gameplay scene that is separated from the individual level scenes. Obviously though most if not all lights are part of levels, so they're in different scenes and automatically get disabled whenever the game starts.

Otherwise, it's a really great system though - good work!

**Comment by Rtyper** [comment]
Looking at Aura.cs and AuraLight.cs, I think the issue is that the lights are in the active scene and so are being initialized before Aura, so the Instance property hasn't been set yet and the components turn themselves off. I've just commented out the part of AuraLight.cs which disables the component for now.

**Comment by raphael-ernaelsten** [comment]
Yes in this case there is a race condition. The improvement on the static managers will fix these cases
