### ISSUE TITLE
Error importing

### ISSUE THREAD

**Issue by g--o** [raphael-ernaelsten/Aura#50]
While importing unity froze like 15 minutes or so and at that point I gave up.
Seems like everything was imported fine except for some shader for some reason:

> 
> A default asset was created for 'Assets/Aura/Shaders/ComputeShaders/ComputeDataComputeShader.compute' because the asset importer crashed on it last time.
> You can select the asset and use the 'Assets -> Reimport' menu command to try importing it again, or you can replace the asset and it will auto import again.
>

**Comment by raphael-ernaelsten** [comment]
Read the README
