### ISSUE TITLE
grain in dark areas

### ISSUE THREAD

**Issue by pawelkozakowski** [raphael-ernaelsten/Aura#51]
Hello,

can I remove or decrease grain in dark areas in my game after using Aura Main Component in my Main Camera?

**Comment by raphael-ernaelsten** [comment]
There will be options to disable dithering and jittering in the next update ;)

**Comment by pawelkozakowski** [comment]
wow thank you for quick response :).

When do you plan relase update? (I dont need specific date – just approximation: week, month etc)

**Comment by pawelkozakowski** [comment]
Any chance to distable it by myself before you'll relase update?

**Comment by raphael-ernaelsten** [comment]
You can try to comment the jittering of the grid cells in the
ComputeDataComputeShader.compute :
#if ENABLE_TEMPORAL_REPROJECTION
half3 unjitteredNormalizedLocalPos = normalizedLocalPos.xyz;
JitterPosition(normalizedLocalPos.xyz, id);
#endif
But this will trigger the recompilation of the shader.

And also you can comment the lines with GetBlueNoise inside in the
AuraUsage.cginc. Don't forget to reimport the Aura/Shaders/Shaders folder
then.

It's something like that, just saying this while at friends' I cannot
guarantee the results out of the blue ;-)

2018-07-19 13:21 GMT+02:00 pawelkozakowski <notifications@github.com>:
