### ISSUE TITLE
Transparent material rendering on top of Aura

### ISSUE THREAD

**Issue by grungi-ankhfire** [raphael-ernaelsten/Aura#53]
We are using Aura to have a volumetric spotlight, and are also using Transparent materials in the scene. For some reason, they always seem to be rendered on top of the volumes.
![screenshot from 2018-07-25 13-45-19](https://user-images.githubusercontent.com/1303268/43199182-6eced3a4-9011-11e8-9718-69d331484498.png)
As you can see, the shape on the right cuts through the lighting, altough the object is way behind the light source.

Do you know a workaround for this? If need be, we can try and provide a more streamlined test scene.

And thanks a lot on the amazing work on Aura!

**Comment by grungi-ankhfire** [comment]
So, turns out I should have paid more attention to the docs and such, so apologies!

But if somebody is looking for the answer : you can use the included AlphaBlend shader (duh) or look into the Starting Guide at "Using Aura in your Shaders". Then, you do not need to look like a fool :D

**Comment by raphael-ernaelsten** [comment]
;-)
