### ISSUE TITLE
Android build doesn't work.

### ISSUE THREAD

**Issue by setimets** [raphael-ernaelsten/Aura#7]
I appreciate your project. It's helpful for me. but when I'm trying to build android, the switching of Android doesn't work well. the error log is like under the image.

![problem](https://user-images.githubusercontent.com/5173341/36156152-9f75b4fe-1119-11e8-8a08-a6439bd59598.png)

**Comment by raphael-ernaelsten** [comment]
Read the readme.
Especially where it is specified that Compute Shaders are required. 😉

**Comment by setimets** [comment]
Thanks :)
