### ISSUE TITLE
How to remove Noise/Grain?

### ISSUE THREAD

**Issue by renzkk** [raphael-ernaelsten/Aura#73]
It is possible to completely remove noise/grain when using aura?

**Comment by raphael-ernaelsten** [comment]
sure! for aura pre 1.1 : 

- disable temporal reprojection in the Aura main component on the camera
- Edit the AuraUsage.cginc and replace all the GetBlueNoise(xxx, yyy) by 0. Then reimport the folder Aura/Shaders/Shaders.
