### ISSUE TITLE
Doesn't work with a spawned player

### ISSUE THREAD

**Issue by Dknighter** [raphael-ernaelsten/Aura#75]
Hey, my player object is being spawned in about 3 seconds after the scene loads which means the lights aren't finding the Aura instance and are all disabling. Is there a way to fix this?

**Comment by raphael-ernaelsten** [comment]
you can try the following :

- have your camera created first then attach to the player when it gets created
- or hold the aura components off until the camera is created

There won't be such problems anymore in aura2
