### ISSUE TITLE
It will get stuck in this place.

### ISSUE THREAD

**Issue by AbyssDrop** [raphael-ernaelsten/Aura#77]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
Always add screenshots to help understand your problem.

**System (please complete the following information):**
 - OS: [e.g. Windows 98]
 - Unity version: [e.g. 4.3]
 - Graphic card: [e.g. NVIDIA 7200]
 - Processor: [e.g. Intel Celeron II]
 - RAM: [e.g. 512Mo]

**Additional information**
Add any other information about the problem here.
![2018-10-15_232115](https://user-images.githubusercontent.com/41113316/46990325-57b7ca00-d133-11e8-82dd-851eac9e2bb4.png)

**Comment by raphael-ernaelsten** [comment]
You, sir, know how to make good use of templates...

All I can say is that you should have read the readme...
