### ISSUE TITLE
【Bug report】The file[ComputeDataComputeShader.compute] is getting stuck compiling 

### ISSUE THREAD

**Issue by MkVno2** [raphael-ernaelsten/Aura#79]
To Reproduce Steps to reproduce the behavior:
When I try to import it (including from .unitypackage, copy and paste, click on this file in unity), untiy will be loaded, which usually lasts for 1.5 hours, which is not normal for a small resource. 

Expected behavior A clear and concise description of what you expected to happen：
I personally expect that I have enough time to write this issue before I fully import it.：p

Screenshots Always add screenshots to help understand your problem.
![2000](https://user-images.githubusercontent.com/44113189/47256442-292f4b80-d4b3-11e8-8f48-805e6284ce44.png)
![this one](https://user-images.githubusercontent.com/44113189/47256443-292f4b80-d4b3-11e8-805f-9e1d9fffe7a8.png)

System (please complete the following information):

OS: [win10]
Unity version: [2018.2f13]
Graphic card: [gtx 965m]
Processor: [I7 6700hq]
RAM: [8G]

Additional information Add any other information about the problem here.
The only problem at the moment is that my English level is not very good. Besides this, I still need to investigate carefully.

**Comment by raphael-ernaelsten** [comment]
Please read the readme/description before downloading.

**Comment by raphael-ernaelsten** [comment]
Please read the readme/description before downloading.
