### ISSUE TITLE
MissingReferenceException on Windows Machine

### ISSUE THREAD

**Issue by simonemilano** [raphael-ernaelsten/Aura#8]
MissingReferenceException: The object of type 'ComputeShader' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
UnityEngine.ComputeShader.SetTexture (Int32 kernelIndex, System.String name, UnityEngine.Texture texture) (at C:/buildslave/unity/build/artifacts/generated/common/runtime/ComputeShaderBindings.gen.cs:143)
AuraAPI.Frustum.ComputeData () (at Assets/Aura/Classes/Frustum.cs:188)
AuraAPI.Aura.UpdateFrustrum () (at Assets/Aura/Classes/Aura.cs:351)
AuraAPI.Aura.OnRenderImage (UnityEngine.RenderTexture src, UnityEngine.RenderTexture dest) (at Assets/Aura/Classes/Aura.cs:189)

**Comment by simonemilano** [comment]
Unity version: 2017.3.0f3

**Comment by raphael-ernaelsten** [comment]
You didn't leave the compute shader compile. Read the readme.

**Comment by simonemilano** [comment]
Sorry, you're right!! Wowwww amazing work!!!!!!! Congratulations!!
